### ISSUE TITLE
Воспроизводимая сборка и CI

### ISSUE THREAD

**Issue by artemohanjanyan** [itmo-logic/logic-notes#2]
Хотелось бы иметь универсальный способ сборки конспекта (хотя бы на Linux). Это нужно для того, чтобы не было казусов вроде "у меня собирается, проблема на вашей стороне". Совсем хорошо будет, если это дело ещё и сможет запускаться на каком-нибудь CI и хотя бы проверять, что всё собирается, а в идеале ещё и давать актуальный pdf. Для этого можно, например, использовать docker. [Вот тут](https://github.com/itegulov/category-theory/blob/master/wercker.yml) можно найти пример, но я его не проверял и можно придумать что-нибудь другое.

Ещё надо бы описать, какие именно части texlive (или ещё какие-то пакеты) требуются для сборки и поддерживать этот список актуальным, чтобы люди без Linux не были совсем оставлены за бортом.

Это сугубо техническая задача на неопределённое количество баллов, которое зависит от клёвости вашего решения. Уместен торг.

**Comment by nsychev** [comment]
Для сборки можно юзать [TeX Live](http://tug.org/texlive/), он есть под Windows, Mac и Linux. Я не пробовал, если честно, но как я понял из документации, с ним в комплекте идёт пакетный менеджер [tlmgr](https://www.tug.org/texlive/tlmgr.html). Если я правильно понимаю, то это примерно то же самое, что и Cabal в Haskell. При этом можно использовать Makefile для сборки, это почти кроссплатформенное решение. В таком случае случае одна из целей будет называться как-то вроде `deps` и устанавливать зависимости.

Также нужно прикрутить CI (думаю, Travis даже пойдет: [пример](https://github.com/PHPirates/travis-ci-latex-pdf)), который будет на каждый пулл-реквест / изменение запускать сборку и блокировать изменения, не проходящие сборку.

Помимо этого, публикацию самой PDF можно сделать так:
* повесить [webhook](https://developer.github.com/v3/activity/events/types/#pushevent) на событие `push` в ветку `master`
* по срабатыванию собрать PDF на удаленном сервере
* закоммитить получившийся файл в ветку `gh-pages`

Таким образом, свежий PDF будет автоматически публиковаться на сайт, что кажется даже удобнее, чем в самом репозитории. Пока не уверен, но возможно это можно также сделать через CI, но если нет, то можно написать отдельное приложение и повесить на какой-нибудь Heroku.

**Comment by nsychev** [comment]
Демо: https://github.com/itmo-logic-test/logic-ci

## Авто-публикация PDF
Пример: [коммит в master](https://github.com/itmo-logic-test/logic-ci/commit/6c53e02) → [деплой](https://circleci.com/gh/itmo-logic-test/logic-ci/15) → [коммит в gh-pages](https://github.com/itmo-logic-test/logic-ci/commit/e97cbe)

## Проверка пулл-реквестов
Пример 1: [пулл-реквест](https://github.com/itmo-logic-test/logic-ci/pull/1) → [собранный PDF (notes)](https://circleci.com/gh/itmo-logic-test/logic-ci/13#artifacts/containers/0)
Пример 2: [упавшая сборка](https://circleci.com/gh/itmo-logic-test/logic-ci/12)

**Comment by artemohanjanyan** [comment]
Done in 9125786ca21397842292527e1801c94bd8b479e7
